Repository Gwardia-Czapli/GwardiaHub, pull requests merged in 2024-05, with the labels that each got.

#61 Design panel for gwardia app (#38)
  core/templates/core/base.html
  core/templates/core/index.html
  core/templates/core/panel.html
  core/templates/core/profile.html
  gwardia/templates/gwardia/index.html
  gwardia/templates/gwardia/list_events.html
  gwardia/views.py
  static/tailwind_custom_styles.js
Labels: type: feature, difficulty: hard

#71 enhancement: Reorganized navbar #70
  .gitignore
  core/context_processors.py
  core/templates/core/base.html
  core/templates/core/index.html
  core/templates/core/panel.html
  core/templates/core/profile.html
  core/urls.py
  core/views.py
  gwardia/templates/components/list_events.html
  gwardia/templates/gwardia/meetings.html
  gwardia/templatetags/list_events.py
  gwardia/urls.py
  gwardia/views.py
  gwardia_hub/settings.py
  gwardia_hub/urls.py
  poetry.lock
Labels: type: enhancement, difficulty: medium, Blocking

#80 Feat: Created `genshin` app
  core/context_processors.py
  genshin/__init__.py
  genshin/admin.py
  genshin/apps.py
  genshin/migrations/__init__.py
  genshin/models.py
  genshin/templates/genshin/index.html
  genshin/tests.py
  genshin/urls.py
  genshin/views.py
  gwardia_hub/settings.py
  gwardia_hub/urls.py
Labels: type: feature, difficulty: easy

#81 feat: added favicon, long logo and normal logo
  core/templates/core/base.html
  core/templates/core/index.html
  core/templates/core/panel.html
  static/images/favicon.png
  static/images/logo.svg
  static/images/long_logo.svg
Labels: type: enhancement, difficulty: medium

#69 Feat/error pages
  core/templates/core/error.html
  core/views.py
  gwardia_hub/urls.py
  static/images/403_image.png
  static/images/404_image.png
  static/images/500_image.png
Labels: type: feature, difficulty: medium

#82 gh webhook signature unit test
  core/gh_webhook_handling.py
  core/tests.py
Labels: type: enhancement, difficulty: medium

#85 Enhancement: OG meta tags
  core/templates/core/base.html
Labels: type: enhancement, difficulty: easy

#86 enhancement: font
  core/templates/core/base.html
  static/tailwind_custom_styles.js
Labels: type: enhancement, difficulty: easy
