Repository Gwardia-Czapli/GwardiaHub, pull requests merged in 2024-04, with the labels that each got.

#28 enhancement: Website hosting (#20)
  build.sh
  core/migrations/0002_alter_nextmeeting_date_of_meeting.py
  gwardia_hub/settings.py
  poetry.lock
  pyproject.toml
  render.yaml
Labels: type: enhancement, difficulty: hard

#35 enhancement: Database in docker (#27)
  README.md
  docker-compose.yml
Labels: type: enhancement, difficulty: easy

#34 feat: Upcoming meetings list on gwardia/index (#23)
  core/templates/core/base.html
  gwardia/models.py
  gwardia/templates/gwardia/index.html
  gwardia/views.py
  poetry.lock
  static/GwardiaHub/tailwind_custom_styles.js
  tailwind.config.js
Labels: type: feature, difficulty: medium

#44 fix: Fixed bug with DEBUG not having default value
  gwardia_hub/settings.py
Labels: type: bug, difficulty: easy, Blocking

#48 enhancement: Open meta tags
  core/templates/core/base.html
Labels: type: enhancement, difficulty: easy

#55 fix: Changed migrations order
  gwardia/migrations/0003_rename_nextmeeting_meeting.py
  gwardia/migrations/0004_rename_date_of_meeting_nextmeeting_date.py
Labels: type: bug, help wanted, Blocking

#26 Feat: Links
  core/templates/core/index.html
  gwardia/urls.py
Labels: type: feature, difficulty: medium

#57 bug: Navbar doesn't work in /gwardia
  core/templates/core/base.html
  core/templates/core/index.html
  core/urls.py
Labels: type: bug, difficulty: easy

#62 feat: Profile page
  core/templates/core/base.html
  core/templates/core/profile.html
  core/templatetags/__init__.py
  core/templatetags/core_extras.py
  core/urls.py
  core/views.py
  static/GwardiaHub/tailwind_custom_styles.js
  static/images/placeholder_profile_pic.png
  static/tailwind_custom_styles.js
Labels: type: feature, difficulty: medium
